### ISSUE TITLE
Tag snapshots with the name of the volume

### ISSUE THREAD

**Issue by mdmallardi** [xombiemp/ec2-take-snapshots-lambda#2]
Hi, I'm not seeing any way to generate a snapshot tag based on dynamic information as written taken from the volume.  I would like it if the snapshot was tagged with the name of the volume, for example. (To make searching through backups more convenient)

**Comment by AjeetK** [comment]
@mdmallardi I have added this feature to my forked repo - https://github.com/AjeetK/ec2-take-snapshots-lambda

**Comment by xombiemp** [comment]
This was implemented in https://github.com/xombiemp/ec2-take-snapshots-lambda/commit/1b9b0417ecaac4d5c508d56fa3e1bf52d1b7e8e0
